version: '3'

services:
  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    networks:
      - devopsnetwork
    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot service
  springboot-app:
    image: lahdid/devops:back
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - devopsnetwork

  # Angular service
  angular-app:
    image: lahdid/devops:front
    ports:
      - "4200:4200"
    depends_on:
      - springboot-app
    networks:
      - devopsnetwork

networks:
  devopsnetwork:

volumes:
  mysql-data:
